# Generated by Django 5.0.7 on 2024-09-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_alter_product_category_subcategory_and_more'),
    ]

    operations = [
    ]
